insurance:
  provider:
   url: http://localhost:8080/insurance-service/getAllPlans
   
microservice:
    details: A superb one Maxy

eureka:
 instance:
   preferIpAddress: true
 client:
  serviceUrl:
   defaultZone: http://localhost:8761/eureka
